name: check
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      clean:
        description: Ignore caches and run a full build and all checks
        type: boolean
        default: false
permissions:
  contents: read
concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  desktop:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        shard: ['0/2', '1/2']
    runs-on: ${{ matrix.os }}
    env:
      ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
      ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/ci
        id: ci
        with:
          clean: ${{ inputs.clean || false }}
          base: ${{ github.event.pull_request.base.sha || github.event.before || '' }}
          shard: ${{ matrix.shard }}
      - run: npx electron-builder --dir --config.mac.identity=-
        shell: bash
        if: steps.ci.outputs.build == 'true' && matrix.shard == '0/2'
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
